local theme = {}

theme.current = {
    name = "default",
    desktop_bg = colors.blue,
    desktop_fg = colors.white,
    taskbar_bg = colors.gray,
    taskbar_fg = colors.white,
    taskbar_active = colors.lightGray,
    window_bg = colors.white,
    window_fg = colors.black,
    titlebar_bg = colors.lightBlue,
    titlebar_fg = colors.black,
    titlebar_inactive_bg = colors.lightGray,
    titlebar_inactive_fg = colors.gray,
    border_color = colors.gray,
    button_bg = colors.lightGray,
    button_fg = colors.black,
    button_hover = colors.white,
    input_bg = colors.white,
    input_fg = colors.black,
    input_border = colors.gray,
    menu_bg = colors.white,
    menu_fg = colors.black,
    menu_hover = colors.lightBlue,
    scrollbar_bg = colors.lightGray,
    scrollbar_fg = colors.gray,
    shadow = colors.black,
    accent = colors.blue,
    error = colors.red,
    success = colors.green,
    warning = colors.yellow,
}

theme.presets = {
    default = {
        name = "default",
        desktop_bg = colors.blue,
        desktop_fg = colors.white,
        taskbar_bg = colors.gray,
        taskbar_fg = colors.white,
        taskbar_active = colors.lightGray,
        window_bg = colors.white,
        window_fg = colors.black,
        titlebar_bg = colors.lightBlue,
        titlebar_fg = colors.black,
        titlebar_inactive_bg = colors.lightGray,
        titlebar_inactive_fg = colors.gray,
        border_color = colors.gray,
        button_bg = colors.lightGray,
        button_fg = colors.black,
        button_hover = colors.white,
        input_bg = colors.white,
        input_fg = colors.black,
        input_border = colors.gray,
        menu_bg = colors.white,
        menu_fg = colors.black,
        menu_hover = colors.lightBlue,
        scrollbar_bg = colors.lightGray,
        scrollbar_fg = colors.gray,
        shadow = colors.black,
        accent = colors.blue,
        error = colors.red,
        success = colors.green,
        warning = colors.yellow,
    },
    dark = {
        name = "dark",
        desktop_bg = colors.black,
        desktop_fg = colors.lightGray,
        taskbar_bg = colors.gray,
        taskbar_fg = colors.white,
        taskbar_active = colors.lightGray,
        window_bg = colors.gray,
        window_fg = colors.white,
        titlebar_bg = colors.black,
        titlebar_fg = colors.white,
        titlebar_inactive_bg = colors.gray,
        titlebar_inactive_fg = colors.lightGray,
        border_color = colors.black,
        button_bg = colors.black,
        button_fg = colors.white,
        button_hover = colors.gray,
        input_bg = colors.black,
        input_fg = colors.white,
        input_border = colors.lightGray,
        menu_bg = colors.gray,
        menu_fg = colors.white,
        menu_hover = colors.black,
        scrollbar_bg = colors.gray,
        scrollbar_fg = colors.lightGray,
        shadow = colors.black,
        accent = colors.cyan,
        error = colors.red,
        success = colors.lime,
        warning = colors.yellow,
    },
    retro = {
        name = "retro",
        desktop_bg = colors.black,
        desktop_fg = colors.lime,
        taskbar_bg = colors.black,
        taskbar_fg = colors.lime,
        taskbar_active = colors.green,
        window_bg = colors.black,
        window_fg = colors.lime,
        titlebar_bg = colors.green,
        titlebar_fg = colors.black,
        titlebar_inactive_bg = colors.black,
        titlebar_inactive_fg = colors.green,
        border_color = colors.green,
        button_bg = colors.black,
        button_fg = colors.lime,
        button_hover = colors.green,
        input_bg = colors.black,
        input_fg = colors.lime,
        input_border = colors.green,
        menu_bg = colors.black,
        menu_fg = colors.lime,
        menu_hover = colors.green,
        scrollbar_bg = colors.black,
        scrollbar_fg = colors.green,
        shadow = colors.black,
        accent = colors.lime,
        error = colors.red,
        success = colors.lime,
        warning = colors.yellow,
    },
}

function theme.apply(presetName)
    local preset = theme.presets[presetName]
    if not preset then return false end
    for k, v in pairs(preset) do
        theme.current[k] = v
    end
    return true
end

function theme.get()
    return theme.current
end

return theme
